Wmi backend
Munich-Quantum-Software-Stack/MQSS-QDMI-Devices-Suite pull request #5
Opened 2024-07-10 12:14 UTC by martin-knudsen

Mostly taken over from the WMI backends created in the QDMI repo. 

One change is the way backends are chosen: This is done now using the QDMI_core_device_count and QDMI_core_open_device functions as can be seen in the test script.

The test script only tests the simulator.

2024-07-10 15:24 UTC, burgholzer requested changes
Hey Martin 👋🏼 
Many thanks for moving the backend over here. Much appreciated!
I just took some time to go over most of the changes here and left some comments inline. Most of these shouldn't be too hard to address and should help to create a cleaner integration.

Note that I haven't particularly checked the backend implementations themselves. As far as I can tell, these will probably require some work in the future when we polished up QDMI and, subsequently, the reference backend integration. Let's try to get this in first and see where we go from there.

2024-07-10 15:24 UTC, burgholzer commented on include/wmi_real.h
Can we move all the WMI-related code to sub-directories?
Specifically, can we place the headers under `include/wmi` and the sources (as well as a dedicated CMake file with all the relevant config) in `src/wmi`?
I believe that would create a better separation of concerns here.

2024-07-10 15:24 UTC, burgholzer commented on include/wmi_real.h
> +#include "private/qdmi_internal.h"
These includes aren't needed here as far as I can tell.
In fact, I am not quite sure whether the include file is needed at all. The shared library itself can certainly still be built without the whole header file here. You should be able to move the gate set definition to the source file.

2024-07-10 15:24 UTC, burgholzer commented on include/wmi_sim.h
Similar considerations as for the real devices backend hold here.

2024-07-10 15:24 UTC, burgholzer commented on src/CMakeLists.txt
As proposed in one of the comments above, the CMake code from here should be moved to a separate `CMakeLists.txt` in the newly-created `src/wmi` folder.
This clearly communicates the requirements and needs of the WMI backend and does not mix them with the remaining code here.

2024-07-10 15:24 UTC, burgholzer commented on src/CMakeLists.txt
> +find_package(cJSON REQUIRED)
Is there a particular reason for why you cannot use the `jansson` dependency that is already requested above for handling JSON?

2024-07-10 15:24 UTC, burgholzer commented on include/wmi_sim.h
> +#include "private/qdmi_internal.h"
It strikes me as counterintuitive that you are importing a private header here. 
Just out of gut feeling, that should not be required to implement a backend.
However, I could imagine that this is due to the current design of QDMI. I am in the process of working on the QDMI repository itself trying to clean up the setup.
This will most likely require some changes in this repository anyways. However, that should definitely not stop us from moving forward here and getting this merged. We can always adapt to new QDMI versions whenever they are ready. So feel free to resolve this conversation for now.

2024-07-10 20:30 UTC, kayaercument commented on include/wmi_sim.h
> +#include "private/qdmi_internal.h"
Hey Lukas 👋🏼

Thank you for your comment. This is a concern of mine, too. `qdmi_internal.h` has details of the implementations, such as `QDMI_Fragment.` Without including the header, we cannot assign it to `qirmod`, etc. What do you think about this?

FYI @echavarria-lrz @mnfarooqi

2024-07-10 20:32 UTC, kayaercument commented on include/wmi_real.h
Do you think we should separate device by device or vendor by vendor? I think `src/wmi/real/` and `src/wmi/sim/` can be easier to manage.

2024-07-10 21:00 UTC, burgholzer commented on include/wmi_sim.h
> +#include "private/qdmi_internal.h"
Yeah. I figured it's needed at the moment.
Once I am done with the QInfo repo, I will switch over to the QDMI repo and try to clean stuff up there. Until then, I think we should just keep including the private header.

2024-07-10 21:02 UTC, burgholzer commented on include/wmi_real.h
Hm. Good point 👍🏻
Could make sense to separate the source files into different folders per backend and keep a CMakeLists.txt per vendor.
I am open to other suggestions though 😌

2024-07-17 13:11 UTC, kayaercument commented
@burgholzer Hey Lukas 👋🏼. There are not as many changes as Github shows, most of them are relocation. I notice the CMakeLists.txt files after pushing. If the organisation looks good, I will clean them up .

2024-07-25 09:00 UTC, burgholzer requested changes
Sorry for the delay here. Still catching up on stuff from vacation.
Many thanks for your changes.
I added some further comments inline.
In general, please remove code instead of just commenting it out and try to make sure that your files contain newlines at the end (GitHub actually shows you this with a red stop sign)

Please also resolve the conflicts with the main branch 😌

2024-07-25 09:00 UTC, burgholzer commented on CMakeLists.txt
> +#add_definitions(${LLVM_DEFINITIONS})
please remove any commented code.

2024-07-25 09:00 UTC, burgholzer commented on cmake/Findqinfo.cmake
> +set(QINFO_INCLUDE_DIRS "${qinfo_SOURCE_DIR}/include")
These lines should not be necessary. 
The QInfo target directly propagates its include directories when linking against it.

This file is also missing a newline at the end of the file.

2024-07-25 09:00 UTC, burgholzer commented on cmake/Findcjson.cmake
> +set(CJON_INCLUDE_DIRS "${cjson_SOURCE_DIR}/")
These lines should not be necessary and the file is also missing a newline at the end of the file.

2024-07-25 09:00 UTC, burgholzer commented on include/wmi/real/wmi_real.h
> +#include "private/qdmi_internal.h"
Commented that before, but these includes should probably be moved to the source file as they are not used here. Same for the other WMI backend

2024-07-25 09:00 UTC, burgholzer commented on CMakeLists.txt
> +find_package(cjson REQUIRED)
Please move these to the `src` folder or its subfolders (if a dependency is only used by one of the backends).

2024-07-25 09:00 UTC, burgholzer commented on src/CMakeLists.txt
> +#find_package(qdmi REQUIRED)
please remove the commented out code here and add a newline at the end of the file.

2024-07-25 09:00 UTC, burgholzer commented on src/ibm/CMakeLists.txt
> +target_link_libraries(backend_ibm PUBLIC qdmi jansson)
```suggestion
find_package(jansson REQUIRED)

add_library(backend_ibm SHARED ibm.c)
target_include_directories(backend_ibm PUBLIC ${CMAKE_SOURCE_DIR}/include/ibm ${QDMI_SRC_DIRS})
target_link_libraries(backend_ibm PUBLIC qdmi jansson)
```
This should be enough for now.
In the future, we should not be relying on internal header details and the `${QDMI_SRC_DIRS}` should be gone as well.

Please also remove the commented out code and add a new line at the end of the file.

Please apply a similar reasoning to the other CMake files.

2024-07-25 09:00 UTC, burgholzer commented on tests/wmi/CMakeLists.txt
> +target_link_libraries(WMIBackend backend_wmi_sim)
```suggestion
target_link_libraries(WMIBackend PRIVATE backend_wmi_sim)
```

2024-07-30 17:31 UTC, burgholzer approved these changes
Many thanks for your work on this! 🙏🏼 

While this was going in the right direction, there were still some unresolved conversations and the overall setup was not yet really ideal.
Instead of giving yet another round of feedback comments, I just pushed a couple of commits that cleanup most of the repository and make this ready to merge.
- First and foremost, the CMake structure is refactored, cleaned up, and streamlined
- In addition, the completely redundant header files have been removed. QDMI backends can simply live in a `.c` file
- Last, but certainly not least, the dependency management has been updated, fixed, and streamlined.

With these changes, the repository is in a much better shape than before. The backends themselves and the corresponding tests need some work in the future, but the current status is good enough to merge the PR and continue the work in follow-up PRs.

2024-07-30 17:32 UTC, merged